#Postgresql configuration server render
spring.datasource.url=jdbc:postgresql://dpg-d96q2uuq1p3s73fp9gm0-a.ohio-postgres.render.com/finanzasn01
spring.datasource.username=finanzasn01_user
spring.datasource.password=Kia8mlZss5C7aC4D7Is5qnZtG7AEHYDB